---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.4
  - name: centos-6.9

suites:
  - name: default
    run_list:
      - recipe[statsd::default]
    attributes:
