---
driver:
  name: docker
  hostname: statsd.local
  privileged: true
  use_sudo: false
  disable_upstart: false
  binary: /usr/bin/docker
  run_command: /sbin/init
  provision_command:
    - mkdir -p /var/run/sshd

driver_config:
  image: ubuntu-upstart:14.04

provisioner:
  client_rb:
    file_atomic_update: false

suites:
  - name: default
    run_list:
    - recipe[statsd::default]
